### ISSUE TITLE
Errors when running the terraform

### ISSUE THREAD

**Issue by vslegers** [alexott/dlt-files-in-repos-demo#1]
Hello Alex, 

First of all, thanks for the interesting demo! I'm currently working on CICD for DLT pipelines.

I was trying to go through the demo but ran into issues when executing the terraform code (attached screenshot) and not sure how to proceed. Could you please have a look and offer some guidance? 

![image](https://user-images.githubusercontent.com/83960587/219412546-b91aca5a-5ba6-42d7-a0e7-0bc48f049933.png)

Thanks in advance!

Kind regards,
Vincent

**Comment by alexott** [comment]
You need to use one of the authenticaiton methods as it's described in the [terraform provider documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication). I'll update README.

**Comment by vslegers** [comment]
Hello Alex, thanks for the quick response! 

I managed to run largest part of the terraform code now. I see the resources have been created in Databricks (dev/staging/prod repos and DLT pipeline(s)). 

Also the Azure DevOps project was deployed but I believe there is still an issue because I cannot see the Build Pipeline or Repo in the project. Can this be connected to error I received at the end of terraform execution?
![image](https://user-images.githubusercontent.com/83960587/219619990-a25817e1-352e-4628-915e-be645e518bf8.png)

I tried manually creating and running the Build Pipeline from the YAML in the repo but also get an error on Variable group not being found.
![image](https://user-images.githubusercontent.com/83960587/219620336-969f214d-0f7d-4b1c-af4c-e49a8629f633.png)

Can you offer some guidance on how I can mitigate these issues? Thanks a lot in advance.

Kind regards,
Vincent

**Comment by alexott** [comment]
if you do it manually, you need to create a variable group with name `DLT Files In Repos Testing` and populated it with all variables listed here: https://github.com/alexott/dlt-files-in-repos-demo/blob/main/terraform/azuredevops/devops.tf#L47

**Comment by vslegers** [comment]
Ok, I will try that. Thanks again for the quick response!

**Comment by SolitanReiska** [comment]
Hi Alex, thanks for the repo. concerning this case here, I suggest adding a default authentication method to main.tf with databricks_url and databricks_pat and 
 - add that option into the provider block of main.tf
```
 provider "databricks" {
  host  = var.databricks_workspace_url
  token = var.databricks_pat
}
```
 - to the variable.tf

**Comment by alexott** [comment]
It’s mentioned in the readme that you need to configure authentication. The suggested method doesn’t work for my workflows, as for me it’s easier to specify environment variable pointing to a given profile than to change parameters…

**Comment by SolitanReiska** [comment]
That's what I mean. A pro like you knows either way what to do and can quickly remove parameter from the provider block, but somebody not so familiar with this flow has everything rigged without studying TF auth methods.

**Comment by SolitanReiska** [comment]
Or maybe add that case as example to the README.md 

Authentication example with Databricks personal access token:
 1. Add additional variables to the `terraform.tfvars`
	`databricks_url` - URL of your existing Databricks Workspace, like, `https://adb-3946431527987256.16.azuredatabricks.net`
	`databricks_pat` - Databricks personal access token (PAT) obtained as described in [documentation](https://docs.databricks.com/en/dev-tools/auth.html#databricks-personal-access-tokens-for-workspace-users).
 2. Add the variables to `variables.tf`
```
 variable "databricks_workspace_url" {
  description = "Databricks URL"
  type        = string
}

variable "databricks_pat" {
  description = "Databricks PAT"
  type        = string
}
```
 3. Add the variable reference into the databricks provider block in `main.tf` like
```
provider "databricks" {
  host  = var.databricks_workspace_url
  token = var.databricks_pat
}
```
